if (!"pacman" %in% installed.packages()) {
  install.packages("pacman")
}
require(pacman)
p_load(
  FinancialInstrument,
  PerformanceAnalytics,
  TTR,
  devtools,
  dplyr,
  ggplot2,
  magrittr,
  quantmod,
  rsvg
)
p_load_gh(
  "IlyaKipnis/IKTrading",
  "braverock/blotter",
  "braverock/quantstrat",
  "dominikduda/candlePlotter"
)
